# Generated by Django 2.2.3 on 2019-07-14 13:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rank', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='RankData',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.CharField(max_length=32)),
                ('count', models.IntegerField(default=0)),
                ('cache_date', models.DateField()),
            ],
        ),
    ]
